# Generated by Django 2.0.7 on 2018-08-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=250)),
                ('file_name', models.CharField(max_length=300)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
