# Generated by Django 2.0.7 on 2018-08-14 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_filedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileData',
        ),
        migrations.AddField(
            model_name='file',
            name='file_key',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
