# Generated by Django 2.0.7 on 2018-09-02 13:03

import account.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20180814_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll', models.CharField(max_length=250)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(default='', upload_to='', validators=[account.validators.validate_file_size], verbose_name=''),
        ),
    ]
