# Generated by Django 2.0.7 on 2018-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180902_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleague',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
