# Generated by Django 2.0.7 on 2018-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180902_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=250)),
                ('receiver', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=0)),
                ('file_id', models.IntegerField(default=0)),
            ],
        ),
    ]
