# Generated by Django 2.0.7 on 2018-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_sendfile_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
