# Generated by Django 2.0.7 on 2018-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_blockcolleague'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_ext',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
